#ifndef MMN14_ADDRESSING_MODES_H
#define MMN14_ADDRESSING_MODES_H


typedef enum {
    IMMEDIATE,
    DIRECT,
    INDIRECT_REGISTER,
    DIRECT_REGISTER
} addressing_mode;

#endif //MMN14_ADDRESSING_MODES_H
